"""Versioned configuration for the logistics-aware embedding model."""

MODEL_VERSION = "logistics_embedding_v2"
MAX_CLUSTER_SIZE = 5

NODE_FEATURE_DIM = 17
EDGE_FEATURE_DIM = 15
HIDDEN_DIM = 128
EMBEDDING_DIM = 64
NUM_GNN_LAYERS = 3
NUM_HEADS = 4
DROPOUT = 0.1

DISTANCE_SCALE_KM = 10.0
TIME_SCALE_MIN = 120.0
DAY_SCALE_MIN = 1440.0

LR = 3e-4
WEIGHT_DECAY = 1e-5
EPOCHS = 100
BATCH_SIZE = 16
GRAD_CLIP = 1.0
FOCAL_GAMMA = 2.0
MAX_POS_WEIGHT = 50.0
CONTRASTIVE_WEIGHT = 0.30
CONTRASTIVE_MARGIN = 0.20
HARD_NEGATIVE_RATIO = 4
VALIDATION_FRACTION = 0.20

DEVICE = "cuda"
SEED = 42

